### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by askingalot** [MandasK/ShootingDice#1]
Make this a private field. There's no need to recreate the list each time the method is called.
https://github.com/MandasK/ShootingDice/blob/48f2dba9a40a7f0daeb34c19b9d66d52212315b8/CreativeSmackTalkingPlayer.cs#L12-L19

Putting the taunt logic in the `Play()` method does meet the requirement, but what if you put it in the `Roll()` method? That would cause the player to taunt in all cases.
https://github.com/MandasK/ShootingDice/blob/48f2dba9a40a7f0daeb34c19b9d66d52212315b8/CreativeSmackTalkingPlayer.cs#L28

I don't think this is the best place to put the roll logic for a human player
https://github.com/MandasK/ShootingDice/blob/48f2dba9a40a7f0daeb34c19b9d66d52212315b8/HumanPlayer.cs#L13-L14

What happens if one of these players is a sore loser?
https://github.com/MandasK/ShootingDice/blob/48f2dba9a40a7f0daeb34c19b9d66d52212315b8/Program.cs#L114-L122

What happens if `DiceSize` is something other than `6`?
https://github.com/MandasK/ShootingDice/blob/48f2dba9a40a7f0daeb34c19b9d66d52212315b8/UpperHalfPlayer.cs#L13

**Comment by MandasK** [comment]
What happens if one of these players is a sore loser?

`` for (int i = 0; i < maxIndex; i += 2) 
 { 
     Console.WriteLine("-------------------"); 
  
     // Make adjacent players play noe another 
     Player player1 = shuffledPlayers[i]; 
     Player player2 = shuffledPlayers[i + 1]; 
     player1.Play(player2); 
 }``

The player selected as "player1" would have their special parameter run where the player selected as "player2" would not.
